# Generated by Django 3.1.2 on 2020-10-27 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Valor')),
                ('pagamento', models.CharField(max_length=8, verbose_name='Pagamento')),
                ('comprovante', models.FileField(blank=True, upload_to='', verbose_name='Comprovante')),
                ('recibo', models.CharField(blank=True, max_length=255, verbose_name='Recibo')),
                ('status', models.CharField(choices=[('aberto', 'ABERTO'), ('fechado', 'FECHADO')], default='aberto', max_length=7)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VENDA',
                'verbose_name_plural': 'VENDAS',
                'ordering': ['-criado'],
            },
        ),
        migrations.CreateModel(
            name='pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], max_length=7)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CADASTRO',
                'verbose_name_plural': 'CADASTROS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255, verbose_name='Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Preço')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Custo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('fornecedor', models.CharField(blank=True, max_length=255, verbose_name='Fornecedor')),
                ('status', models.CharField(choices=[('disponivel', 'DISPONIVEL'), ('esgotado', 'ESGOTADO')], max_length=10)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PRODUTO',
                'verbose_name_plural': 'PRODUTOS',
                'ordering': ['produto'],
            },
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidadeEstado', models.CharField(max_length=255, verbose_name='Cidade/Estado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('frase', models.CharField(max_length=255, verbose_name='Rodapé')),
                ('status', models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], max_length=7)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EMPRESA',
                'verbose_name_plural': 'EMPRESAS',
                'ordering': ['empresa'],
            },
        ),
    ]
