# Generated by Django 3.1.2 on 2020-10-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='recibo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Recibo'),
        ),
    ]
