# Generated by Django 3.1.1 on 2020-09-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
