# Generated by Django 3.1.2 on 2020-10-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='comprovante',
            field=models.FileField(blank=True, upload_to='', verbose_name='Comprovante'),
        ),
    ]
