# Generated by Django 3.1.4 on 2020-12-06 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Valor')),
                ('relacao', models.CharField(max_length=255, verbose_name='Relação')),
                ('status', models.CharField(choices=[('aberta', 'aberta'), ('fechada', 'fechada'), ('cancelada', 'cancelada')], default='aberta', max_length=9)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saida',
                'verbose_name_plural': 'saidas',
                'ordering': ['-criado'],
            },
        ),
    ]
