# Generated by Django 3.1.1 on 2020-09-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200928_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO')], max_length=7),
        ),
    ]
