# Generated by Django 3.1.4 on 2020-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_saidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.CharField(max_length=255, verbose_name='Produto'),
        ),
    ]
