# Generated by Django 3.1.2 on 2020-10-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200928_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['nome'], 'verbose_name': 'CADASTRO', 'verbose_name_plural': 'CADASTROS'},
        ),
        migrations.AlterField(
            model_name='app',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='app',
            name='endereco',
            field=models.TextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='app',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='app',
            name='telefone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
    ]
