# Generated by Django 3.1.2 on 2020-10-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201015_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255, verbose_name='Produto')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Preço')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Custo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('ativo', 'DISPONIVEL'), ('inativo', 'ESGOTADO')], max_length=10)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PRODUTO',
                'verbose_name_plural': 'PRODUTOS',
                'ordering': ['produto'],
            },
        ),
        migrations.RenameModel(
            old_name='app',
            new_name='pessoas',
        ),
    ]
