# Generated by Django 3.1.2 on 2020-10-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201016_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='status',
            field=models.CharField(choices=[('disponivel', 'DISPONIVEL'), ('esgotado', 'ESGOTADO')], max_length=10),
        ),
    ]
