# Generated by Django 3.1.2 on 2020-10-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201017_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='observacao',
            field=models.TextField(default=1, verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
    ]
