# Generated by Django 3.1.2 on 2020-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_estoque_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
