# Generated by Django 3.1.2 on 2020-10-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_estoque_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=999, verbose_name='Valor')),
                ('pagamento', models.CharField(max_length=8, verbose_name='Pagamento')),
                ('comprovante', models.FileField(upload_to='pdf', verbose_name='Comprovante')),
                ('status', models.CharField(choices=[('aberto', 'ABERTO'), ('fechado', 'FECHADO')], max_length=7)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'VENDA',
                'verbose_name_plural': 'VENDAS',
                'ordering': ['criado'],
            },
        ),
        migrations.AddField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(default=0, max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='atualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='atualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
