# Generated by Django 3.1.2 on 2020-10-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201019_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='comprovante',
            field=models.FileField(blank=True, upload_to='pdf', verbose_name='Comprovante'),
        ),
    ]
