# Generated by Django 3.1.2 on 2020-10-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201020_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'ordering': ['-criado'], 'verbose_name': 'VENDA', 'verbose_name_plural': 'VENDAS'},
        ),
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cliente'),
        ),
    ]
