# Generated by Django 3.1.2 on 2020-10-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201020_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='comprovante',
            field=models.FileField(blank=True, upload_to='static/archive/pdf', verbose_name='Comprovante'),
        ),
    ]
