# Generated by Django 3.1.2 on 2020-10-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201020_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='status',
            field=models.CharField(choices=[('aberto', 'ABERTO'), ('fechado', 'FECHADO')], default='aberto', max_length=7),
        ),
    ]
