# Generated by Django 3.1.2 on 2020-10-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201020_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cliente'),
        ),
    ]
