# Generated by Django 3.1.2 on 2020-10-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201021_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='comprovante',
            field=models.FileField(blank=True, upload_to='pdf', verbose_name='Comprovante'),
        ),
    ]
