# Generated by Django 3.1.2 on 2020-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201021_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='recibo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cliente'),
        ),
    ]
